### ISSUE TITLE
一个问题：如何hide一个没有名称标签的托盘图标

### ISSUE THREAD

**Issue by shanghaox** [LCiZY/HideTrayIcon#3]
请问如果我需要hide一个没有名称的托盘图标，直接搜寻进程名字可行吗，请问需要如何修改代码以实现？/salute

**Comment by LCiZY** [comment]
可以的，看这里：https://stackoverflow.com/questions/4570174/how-to-get-the-process-name-in-c

**Comment by LCiZY** [comment]
util.cpp中的td.hWnd就是托盘的句柄，通过
```
DWORD trayProcessId = 0; GetWindowThreadProcessId(td.hWnd, &trayProcessId); 
```
拿到对应进程ID，再通过
```

std::string ProcessIdToName(DWORD processId)
{
	std::string ret;
	HANDLE handle = OpenProcess(
		PROCESS_QUERY_LIMITED_INFORMATION,
		FALSE,
		processId /* This is the PID, you can find one from windows task manager */
	);
	if (handle)
	{
		DWORD buffSize = 1024;
		CHAR buffer[1024];
		if (QueryFullProcessImageNameA(handle, 0, buffer, &buffSize))
		{
			ret = buffer;
		}
		else
		{
			printf("Error GetModuleBaseNameA : %lu", GetLastError());
		}
		CloseHandle(handle);
	}
	else
	{
		printf("Error OpenProcess : %lu", GetLastError());
	}
	return ret;
}
```
就能拿到进程名称了

**Comment by shanghaox** [comment]
respect，非常感谢，得到如此详细的solution，我是一名cs大一学生，对windows api完全不懂，也不会stl，趁这个机会上次翻了stackoverflow也并不能解决问题,有些代码很老了。同时还不是很习惯看文档，windows api文档虽然让我开眼界，但还不会stl，看不下去，我这就去apply你的code！
&nbsp;


谢轩豪Charlie
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月13日(星期五) 晚上7:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LCiZY/HideTrayIcon] 一个问题：如何hide一个没有名称标签的托盘图标 (Issue #3)





 
util.cpp中的td.hWnd就是托盘的句柄，通过
 DWORD trayProcessId = 0; GetWindowThreadProcessId(td.hWnd, &amp;trayProcessId);   
拿到对应进程ID，再通过
  std::string ProcessIdToName(DWORD processId) { 	std::string ret; 	HANDLE handle = OpenProcess( 		PROCESS_QUERY_LIMITED_INFORMATION, 		FALSE, 		processId /* This is the PID, you can find one from windows task manager */ 	); 	if (handle) 	{ 		DWORD buffSize = 1024; 		CHAR buffer[1024]; 		if (QueryFullProcessImageNameA(handle, 0, buffer, &amp;buffSize)) 		{ 			ret = buffer; 		} 		else 		{ 			printf("Error GetModuleBaseNameA : %lu", GetLastError()); 		} 		CloseHandle(handle); 	} 	else 	{ 		printf("Error OpenProcess : %lu", GetLastError()); 	} 	return ret; }  
就能拿到进程名称了
 
&mdash;

**Comment by shanghaox** [comment]
不过Todesk没有名字标签，log输出的名字是空的。请问有办法通过ToDesk.exe 的名字定位到窗口不？

**Comment by LCiZY** [comment]
我新提交了一版代码，你看看是不是能满足你的要求

**Comment by shanghaox** [comment]
ok了 强！感谢大佬
