### ISSUE TITLE
隐藏图标后托盘变成长条状

### ISSUE THREAD

**Issue by valscox** [LCiZY/HideTrayIcon#5]
![image](https://user-images.githubusercontent.com/69556370/183016809-396f2a9a-2e3b-4a21-8572-95f7025b4f1a.png)    ![image](https://user-images.githubusercontent.com/69556370/183017305-19a841ea-05b2-4cb7-ac0a-368f7a4cea34.png)
如图，隐藏部分图标后托盘没有变成矩形，而是所有剩余图标竖向排列，请问是该程序导致的吗，可以修复吗

**Comment by zuohaoda** [comment]
Win11遇到同样的问题

**Comment by LCiZY** [comment]
嗯，这是个小bug，当`SetTrayIconVisable`这个函数的isHardDelete参数为false时，会有这个问题，现在已经更改了默认行为，将isHardDelete设为true。
```c++
VOID SetTrayIconVisable(HWND hWnd, std::vector<std::string>& process_name_or_tooltips, bool visible, bool isHardDelete)
isHardDelete为true：发送NIM_DELETE消息，将托盘图标删除，等资源管理器重启才会再次显示
isHardDelete为false：发送hide消息，将托盘隐藏，可以通过发送show消息重新显示，等资源管理器重启也会再次显示。
现在通过发送hide消息隐藏图标的方法就会造成这个bug，所以现在更改默认行为为发送NIM_DELETE消息，就不会有这个问题
```

**Comment by LCiZY** [comment]
通过发送hide消息隐藏图标会造成长条形状托盘，现在还没有弄清具体原因，应该跟Windows系统实现有关。目前的解决办法就是发送NIM_DELETE消息直接删除图标了。

**Comment by LCiZY** [comment]
> ![image](https://user-images.githubusercontent.com/69556370/183016809-396f2a9a-2e3b-4a21-8572-95f7025b4f1a.png) ![image](https://user-images.githubusercontent.com/69556370/183017305-19a841ea-05b2-4cb7-ac0a-368f7a4cea34.png) 如图，隐藏部分图标后托盘没有变成矩形，而是所有剩余图标竖向排列，请问是该程序导致的吗，可以修复吗

现在解决了，可以再试试

**Comment by LCiZY** [comment]
> Win11遇到同样的问题

现在解决了，可以再试试
